### ISSUE TITLE
还是报错，获取不到信息

### ISSUE THREAD

**Issue by Ariken2002** [xiaoxiunique/x-kit#4]
bun run scripts/index.ts
🚀 ~ cookieObj ~ cookieObj: {
  "guest_id": "v1%3A1735302758688737727",
  "twid": "u%3D803867578565173248",
  "ct0": "f1b3363782c1fe119cfaf90232323769a1a7de0a27942232323206d5a2ce436b2519c3ed8b2be6231122212ce827a9ca5123a5d623e8f43d734538823cdce84129434023977433d23c434b5d014"
}
Error fetching Michael Anti: 28 | };
29 | exports.getKwargs = getKwargs;
30 | var errorCheck = function (data, error) {
31 |     var _a;
32 |     if (data == undefined) {
33 |         throw Error((_a = error === null || error === void 0 ? void 0 : error.map(function (e) { return e.message; }).join(', ')) !== null && _a !== void 0 ? _a : 'No data');
                   ^
error: No data
      at errorCheck (C:\Users\Desktop\x-kit-main\node_modules\twitter-openapi-typescript\dist\src\utils\api.js:33:15)
      at C:\Users\Desktop\x-kit-main\node_modules\twitter-openapi-typescript\dist\src\apis\userApi.js:72:37
      at step (C:\Users\Desktop\x-kit-main\node_modules\twitter-openapi-typescript\dist\src\apis\userApi.js:44:23)
      at fulfilled (C:\Users\Desktop\x-kit-main\node_modules\twitter-openapi-typescript\dist\src\apis\userApi.js:16:58)

**Comment by Ariken2002** [comment]
这个结果貌似也不对：
bun run scripts/fetch-tweets.ts
🚀 ~ cookieObj ~ cookieObj: {
  "guest_id": "v1%3A17353029930222468120",
  "twid": "u%3D803867578565173248",
  "ct0": "5889929929922cb503665d6e49dd0d7ca4c35799ef29cbc5a60c632ad12471009723696804716c91de0c60898c19cb5073881f344735d2356fa59467bb91eebb36092d6e1048a38783e8329fa3982"
}

**Comment by xiaoxiunique** [comment]
问题描述不清晰

**Comment by Ariken2002** [comment]
就是配置参数这些都配置好了，结果没有返回推文或者用户信息，bun run scripts/index.ts返回时报错了，bun run scripts/fetch-tweets.ts返回里面，没有推文数据。

**Comment by xiaoxiunique** [comment]
这个 twitter 账号在网页能正常访问吗

**Comment by Ariken2002** [comment]
网页上可以正常访问

**Comment by ZAIDU-Miren** [comment]
你获取的token，是按照教程的嘛，这边测试正常

**Comment by tuber0613** [comment]
我也遇到了同样的问题，网页可以登录但是获取不了用户信息
`🚀 ~ cookieObj ~ cookieObj: {
  "guest_id": "v1%3A174319134342018423",
  "twid": "u%3D1895889862794121216",
  "ct0": "5e482141281fded520734da94befdbfeff10dbd675303507fa96d83f7d80a1bc9f9ef0b30045a5f45ecb88d552a6f25c604883940f1922cbe9f2dac840fe222deb2c695bcaaad651eacf2a67106d2d64",
  "__cf_bm": "_W8sn__vpteXOZikscqJ90okd1IhMn9DzkatM3Wnv2E-1743191343-1.0.1.1-Iu4Vmg2rXAvvKRgcyKg0nAfdx4fJ1wfxJDx2A9CjZQURfO6WbJE6JJ.BnwOPsAySyxCghVHihQw.uyuLSD2ZRE7GLPtoabCT.nj.vQNszdE"
}
Error fetching Shital Shah: 28 | };
29 | exports.getKwargs = getKwargs;
30 | var errorCheck = function (data, error) {
31 |     var _a;
32 |     if (data == undefined) {
33 |         throw Error((_a = error === null || error === void 0 ? void 0 : error.map(function (e) { return e.message; }).join(', ')) !== null && _a !== void 0 ? _a : 'No data');
                   ^
error: No data
      at errorCheck (/home/runner/work/x-kit/x-kit/node_modules/twitter-openapi-typescript/dist/src/utils/api.js:33:15)
      at <anonymous> (/home/runner/work/x-kit/x-kit/node_modules/twitter-openapi-typescript/dist/src/apis/userApi.js:72:37)
      at step (/home/runner/work/x-kit/x-kit/node_modules/twitter-openapi-typescript/dist/src/apis/userApi.js:44:23)
      at fulfilled (/home/runner/work/x-kit/x-kit/node_modules/twitter-openapi-typescript/dist/src/apis/userApi.js:16:58)`
